import SwiftUI
import AVFoundation

// Speech is generated by iOS from the question text. No microphone access,
// remote text-to-speech endpoint, or per-question audio download is involved.
@MainActor
final class V46SpeechReader: NSObject, ObservableObject, AVSpeechSynthesizerDelegate {
    @Published private(set) var speaking = false
    private let synthesizer = AVSpeechSynthesizer()

    override init() {
        super.init()
        synthesizer.delegate = self
    }

    func toggle(_ text: String) {
        if synthesizer.isSpeaking {
            stop()
            return
        }
        let clean = murshidQuestionDisplayText(text).trimmingCharacters(in: .whitespacesAndNewlines)
        guard !clean.isEmpty else { return }
        let utterance = AVSpeechUtterance(string: clean)
        let voices = AVSpeechSynthesisVoice.speechVoices()
        utterance.voice = voices.first(where: { $0.language == "ar-IQ" })
            ?? voices.first(where: { $0.language == "ar-SA" })
            ?? voices.first(where: { $0.language.hasPrefix("ar") })
            ?? AVSpeechSynthesisVoice(language: "ar-SA")
        utterance.rate = 0.46
        utterance.pitchMultiplier = 1.0
        speaking = true
        synthesizer.speak(utterance)
    }

    func stop() {
        if synthesizer.isSpeaking { synthesizer.stopSpeaking(at: .immediate) }
        speaking = false
    }

    nonisolated func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didFinish utterance: AVSpeechUtterance) {
        Task { @MainActor in self.speaking = false }
    }

    nonisolated func speechSynthesizer(_ synthesizer: AVSpeechSynthesizer, didCancel utterance: AVSpeechUtterance) {
        Task { @MainActor in self.speaking = false }
    }
}

struct V46SpeechButton: View {
    @ObservedObject var reader: V46SpeechReader
    let text: String

    var body: some View {
        Button {
            reader.toggle(text)
            selectionHaptic()
        } label: {
            Label(reader.speaking ? "إيقاف القراءة" : "استمع للسؤال", systemImage: reader.speaking ? "stop.circle.fill" : "speaker.wave.2.fill")
                .font(.subheadline.weight(.semibold))
        }
        .buttonStyle(.bordered)
        .accessibilityHint("يقرأ نص السؤال بصوت عربي على الجهاز دون استخدام الميكروفون")
    }
}

enum V46DeckMode {
    case traps
    case golden

    var title: String { self == .traps ? "فخاخ الوزاري" : "البطاقات الذهبية" }
    var subtitle: String {
        self == .traps ? "ميّز الإجابة الصحيحة من الخيار المشتّت." : "اقلب البطاقة لتتذكر الجواب بنفسك."
    }
}

struct V46LearningDeckView: View {
    @EnvironmentObject private var app: AppSession
    let mode: V46DeckMode
    @State private var subjectID = 0
    @State private var topics: [Topic] = []
    @State private var topicID = 0
    @State private var questions: [Question] = []
    @State private var pairOptions: [Int: [QuestionOption]] = [:]
    @State private var current = 0
    @State private var revealed = false
    @State private var selected = ""
    @State private var loading = false
    @State private var loaded = false
    @State private var error = ""
    @StateObject private var speechReader = V46SpeechReader()

    private var presentQuestion: Question? {
        questions.indices.contains(current) ? questions[current] : nil
    }

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 14) {
                V3IntroCard(eyebrow: "تدريب من بنك أسئلة صفّك", title: mode.title, text: mode.subtitle, icon: mode == .traps ? "eye.fill" : "rectangle.on.rectangle.angled")

                MurshidCard {
                    VStack(alignment: .leading, spacing: 12) {
                        Picker("المادة", selection: $subjectID) {
                            Text("اختر المادة").tag(0)
                            ForEach(app.subjects) { s in Text(s.name).tag(s.id) }
                        }
                        .onChange(of: subjectID) { _ in Task { await loadTopics() } }
                        if !topics.isEmpty {
                            Picker("الموضوع", selection: $topicID) {
                                Text("اختر الموضوع").tag(0)
                                ForEach(topics) { t in Text(t.name).tag(t.id) }
                            }
                        }
                        Button {
                            Task { await loadCards() }
                        } label: {
                            Label(loading ? "جاري تجهيز البطاقات…" : "ابدأ التدريب", systemImage: "play.fill")
                        }
                        .buttonStyle(.borderedProminent)
                        .tint(.murshidBlue)
                        .disabled(loading || topicID == 0)
                    }
                }

                if !error.isEmpty {
                    V3InlineMessage(text: error, icon: "exclamationmark.triangle.fill", tone: .warning)
                }
                if loading { ProgressView().frame(maxWidth: .infinity).padding() }
                if loaded && questions.isEmpty {
                    EmptyStateView(systemImage: "books.vertical", title: "لا توجد بطاقات جاهزة", message: "ستظهر البطاقات عندما تتوفر أسئلة منشورة مع إجاباتها الصحيحة لهذا الموضوع.")
                }
                if let q = presentQuestion {
                    MurshidCard {
                        VStack(alignment: .leading, spacing: 14) {
                            HStack {
                                Text("بطاقة \(current + 1) من \(questions.count)")
                                    .font(.caption.bold()).foregroundStyle(Color.murshidBlue)
                                Spacer()
                                V46SpeechButton(reader: speechReader, text: q.text)
                            }
                            Text(murshidQuestionDisplayText(q.text))
                                .font(.title3.bold()).fixedSize(horizontal: false, vertical: true)
                            if mode == .golden {
                                Button {
                                    revealed.toggle()
                                    selectionHaptic()
                                } label: {
                                    VStack(spacing: 10) {
                                        Image(systemName: revealed ? "checkmark.seal.fill" : "rectangle.on.rectangle.angled")
                                            .font(.largeTitle)
                                        Text(revealed ? q.correctAnswer : "اضغط لقلب البطاقة وإظهار الجواب")
                                            .font(.headline)
                                            .multilineTextAlignment(.center)
                                    }
                                    .foregroundStyle(revealed ? Color.green : Color.murshidBlue)
                                    .frame(maxWidth: .infinity, minHeight: 130)
                                    .background(Color.murshidBlue.opacity(0.06), in: RoundedRectangle(cornerRadius: 16))
                                }
                                .buttonStyle(.plain)
                            } else {
                                ForEach(pairOptions[q.id] ?? []) { option in
                                    Button {
                                        guard selected.isEmpty else { return }
                                        selected = option.text
                                        selectionHaptic()
                                    } label: {
                                        HStack {
                                            Text(option.text)
                                            Spacer()
                                            if !selected.isEmpty {
                                                Image(systemName: murshidAnswerKey(option.text) == murshidAnswerKey(q.correctAnswer) ? "checkmark.circle.fill" : "circle")
                                                    .foregroundStyle(murshidAnswerKey(option.text) == murshidAnswerKey(q.correctAnswer) ? .green : .secondary)
                                            }
                                        }
                                        .padding(12)
                                        .background(selected == option.text ? Color.murshidBlue.opacity(0.11) : Color.primary.opacity(0.035), in: RoundedRectangle(cornerRadius: 12))
                                    }
                                    .buttonStyle(.plain)
                                    .disabled(!selected.isEmpty)
                                }
                                if !selected.isEmpty {
                                    Label(murshidAnswerKey(selected) == murshidAnswerKey(q.correctAnswer) ? "أحسنت، تجنّبت الفخ!" : "الخيار الصحيح: \(q.correctAnswer)", systemImage: "lightbulb.fill")
                                        .foregroundStyle(Color.murshidBlue)
                                }
                            }
                            if (revealed && mode == .golden) || (mode == .traps && !selected.isEmpty), !q.explanation.isEmpty {
                                Text(murshidExplanationText(question: q.text, correctAnswer: q.correctAnswer, raw: q.explanation))
                                    .font(.subheadline).foregroundStyle(.secondary)
                            }
                        }
                    }

                    HStack {
                        Button("السابق") { move(-1) }
                            .disabled(current == 0)
                        Spacer()
                        Button(current == questions.count - 1 ? "إعادة التدريب" : "التالي") {
                            move(current == questions.count - 1 ? -current : 1)
                        }
                        .buttonStyle(.borderedProminent).tint(.murshidBlue)
                    }
                    .buttonStyle(.bordered)
                }
            }
            .padding(16)
            .padding(.bottom, 25)
        }
        .background(Color.murshidBackground.ignoresSafeArea())
        .navigationTitle(mode.title)
        .navigationBarTitleDisplayMode(.inline)
        .onAppear { if subjectID == 0 { subjectID = app.subjects.first?.id ?? 0 } }
        .onDisappear { speechReader.stop() }
    }

    private func move(_ offset: Int) {
        current = max(0, min(questions.count - 1, current + offset))
        selected = ""
        revealed = false
        speechReader.stop()
        selectionHaptic()
    }

    private func loadTopics() async {
        await MainActor.run {
            topicID = 0
            topics = []
            questions = []
            loaded = false
            error = ""
        }
        guard subjectID > 0 else { return }
        do {
            let d = try await APIClient.shared.request("mobile/topics.php", query: [URLQueryItem(name: "subject_id", value: "\(subjectID)")], cacheKey: "topics-\(subjectID)")
            await MainActor.run { topics = jArray(d["topics"]).map(Topic.init) }
        } catch {
            await MainActor.run { self.error = error.localizedDescription }
        }
    }

    private func loadCards() async {
        guard topicID > 0 else { return }
        await MainActor.run { loading = true; loaded = false; error = ""; speechReader.stop() }
        do {
            let d = try await APIClient.shared.request("mobile/exam.php", query: [URLQueryItem(name: "chapter_id", value: "\(topicID)")])
            let valid = jArray(d["questions"])
                .map(Question.init)
                .filter { q in
                    guard murshidQuestionClientValid(q), !q.correctAnswer.isEmpty else { return false }
                    if mode == .golden { return true }
                    return q.options.contains(where: { murshidAnswerKey($0.text) == murshidAnswerKey(q.correctAnswer) }) && q.options.count >= 2
                }
            var prepared: [Int: [QuestionOption]] = [:]
            if mode == .traps {
                for q in valid {
                    if let right = q.options.first(where: { murshidAnswerKey($0.text) == murshidAnswerKey(q.correctAnswer) }),
                       let wrong = q.options.first(where: { murshidAnswerKey($0.text) != murshidAnswerKey(q.correctAnswer) }) {
                        prepared[q.id] = [right, wrong].shuffled()
                    }
                }
            }
            await MainActor.run {
                questions = Array(valid.prefix(30))
                pairOptions = prepared
                current = 0
                selected = ""
                revealed = false
                loaded = true
                loading = false
            }
        } catch {
            await MainActor.run { self.error = error.localizedDescription; loading = false; loaded = true; questions = [] }
        }
    }
}

struct V46SharedQuestionRoute: Identifiable {
    let subjectID: Int
    let topicID: Int
    let questionID: Int
    var id: String { "\(subjectID)-\(topicID)-\(questionID)" }
}

struct V46SharedQuestionView: View {
    @EnvironmentObject private var app: AppSession
    @Environment(\.dismiss) private var dismiss
    let route: V46SharedQuestionRoute
    @State private var topic: Topic?
    @State private var loading = true
    @State private var error = ""

    var body: some View {
        Group {
            if loading {
                ProgressView("جاري فتح السؤال…")
            } else if let topic, let subject = app.subjects.first(where: { $0.id == route.subjectID }) {
                V3ExamView(topic: topic, subject: subject, startingQuestionID: route.questionID)
            } else {
                EmptyStateView(systemImage: "lock.shield", title: "السؤال غير متاح", message: error.isEmpty ? "هذا السؤال غير متاح في صفك أو لم يعد منشورًا." : error)
            }
        }
        .navigationTitle("سؤال مشترك")
        .toolbar { ToolbarItem(placement: .topBarLeading) { Button("إغلاق") { dismiss() } } }
        .task {
            guard app.subjects.contains(where: { $0.id == route.subjectID }) else {
                loading = false
                return
            }
            do {
                let data = try await APIClient.shared.request("mobile/topics.php", query: [URLQueryItem(name: "subject_id", value: "\(route.subjectID)")])
                let match = jArray(data["topics"]).map(Topic.init).first(where: { $0.id == route.topicID })
                await MainActor.run { topic = match; loading = false }
            } catch {
                await MainActor.run { self.error = error.localizedDescription; loading = false }
            }
        }
    }
}
