name: MurshidWizari
options:
  bundleIdPrefix: com.muriq
targets:
  MurshidWizari:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [MurshidWizari]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.muriq.murshid
        PRODUCT_NAME: MurshidWizari
        SWIFT_VERSION: 5.0
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: MurshidWizari/Info.plist
